package database

import (
	"os"
	"sync"
	"testing"
	"time"

	"ok-folio/internal/config"

	postgresdriver "gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

// openPostgresTestDB connects to the Postgres instance named by
// OKFOLIO_TEST_POSTGRES_DSN. When the variable is unset the whole suite skips,
// so fast sqlite unit tests stay the default and the real migration is gated by
// CI (a VectorChord/pgvector service container) rather than green sqlite.
func openPostgresTestDB(t *testing.T) *DB {
	t.Helper()

	dsn := os.Getenv("OKFOLIO_TEST_POSTGRES_DSN")
	if dsn == "" {
		t.Skip("set OKFOLIO_TEST_POSTGRES_DSN to run the Postgres-backed integration test")
	}

	gormDB, err := gorm.Open(postgresdriver.Open(dsn), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Silent),
	})
	if err != nil {
		t.Fatalf("Failed to connect to Postgres: %v", err)
	}

	// Start from a clean schema so identity conversion and idempotency are
	// exercised from scratch. The test acts as the stack initdb here: it (and
	// only it) creates the vector extension if the image provides it.
	gormDB.Exec("DROP TABLE IF EXISTS downloaded_photos, extraction_runs, inbox_items CASCADE")
	gormDB.Exec("CREATE EXTENSION IF NOT EXISTS vector")

	return &DB{DB: gormDB}
}

func vectorExtensionPresent(db *DB) bool {
	var present bool
	db.DB.Raw("SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'vector')").Scan(&present)
	return present
}

func TestPostgresMigrateSchemaAndIdempotency(t *testing.T) {
	db := openPostgresTestDB(t)

	if err := Migrate(db.DB); err != nil {
		t.Fatalf("first Migrate failed: %v", err)
	}

	// The favorite column must be the snake_case `favorite`, not a quoted
	// "Favorite": the favorites facet/filter references it directly.
	columns, err := db.DB.Migrator().ColumnTypes(&DownloadedPhoto{})
	if err != nil {
		t.Fatalf("ColumnTypes failed: %v", err)
	}
	names := map[string]bool{}
	for _, c := range columns {
		names[c.Name()] = true
	}
	if !names["favorite"] {
		t.Fatalf("expected a snake_case favorite column, got columns %v", names)
	}
	if names["Favorite"] {
		t.Fatalf("did not expect a quoted \"Favorite\" column")
	}
	for _, required := range []string{"url_hash", "content_hash", "perceptual_hash", "provider", "category"} {
		if !names[required] {
			t.Fatalf("expected column %q present, got %v", required, names)
		}
	}

	// PK is GENERATED BY DEFAULT AS IDENTITY ('d'), never ALWAYS ('a').
	assertIdentityByDefault(t, db)

	// The (downloaded_at, artist) composite exists and the redundant standalone
	// downloaded_at index is dropped.
	if !indexExists(db, "idx_downloaded_photos_downloaded_at_artist") {
		t.Fatalf("expected composite index idx_downloaded_photos_downloaded_at_artist")
	}
	if standaloneDownloadedAtIndexExists(db) {
		t.Fatalf("expected the standalone downloaded_at index to be dropped")
	}

	// The raw url carries no btree (uniqueness lives on url_hash).
	if urlHasBtree(db) {
		t.Fatalf("expected raw url to carry no btree index")
	}

	// Embedding is added via post-migrate Exec when the vector type exists.
	if vectorExtensionPresent(db) && !names2HasEmbedding(t, db) {
		t.Fatalf("expected embedding column to be added when vector extension is present")
	}

	// Second boot is a no-op: AutoMigrate + post-migrate stay idempotent and the
	// identity attribute survives.
	if err := Migrate(db.DB); err != nil {
		t.Fatalf("second Migrate (idempotency) failed: %v", err)
	}
	assertIdentityByDefault(t, db)
}

func TestPostgresILIKESearchAndCompositeOrder(t *testing.T) {
	db := openPostgresTestDB(t)
	if err := Migrate(db.DB); err != nil {
		t.Fatalf("Migrate failed: %v", err)
	}

	base := time.Date(2026, 6, 25, 12, 0, 0, 0, time.UTC)
	photos := []DownloadedPhoto{
		{URL: "https://example.com/a.jpg", Title: "Sunset Over Water", Artist: "Zoe", FileName: "a.jpg", Status: "downloaded", DownloadedAt: base.Add(-2 * time.Hour)},
		{URL: "https://example.com/b.jpg", Title: "City Lights", Artist: "Amy", FileName: "b.jpg", Status: "downloaded", DownloadedAt: base},
	}
	for i := range photos {
		if err := db.Create(&photos[i]).Error; err != nil {
			t.Fatalf("insert failed: %v", err)
		}
	}

	// ILIKE: a lowercase query matches the mixed-case title.
	results, total, err := db.SearchPhotos("sunset", 10, 0)
	if err != nil {
		t.Fatalf("SearchPhotos failed: %v", err)
	}
	if total != 1 || len(results) != 1 || results[0].Title != "Sunset Over Water" {
		t.Fatalf("expected case-insensitive ILIKE match, got total=%d results=%#v", total, results)
	}

	// Composite-index order-by: newest downloaded first.
	catalog, _, err := db.GetGalleryCatalog(10, 0, GalleryCatalogFilters{})
	if err != nil {
		t.Fatalf("GetGalleryCatalog failed: %v", err)
	}
	if len(catalog) != 2 || catalog[0].Title != "City Lights" {
		t.Fatalf("expected newest-first ordering via composite index, got %#v", catalog)
	}
}

func TestPostgresConcurrentSameURLHashRoutesLoserToInbox(t *testing.T) {
	db := openPostgresTestDB(t)
	if err := Migrate(db.DB); err != nil {
		t.Fatalf("Migrate failed: %v", err)
	}

	const sharedURL = "https://example.com/concurrent.jpg"
	var wg sync.WaitGroup
	results := make([]bool, 2)
	errs := make([]error, 2)
	start := make(chan struct{})

	for i := 0; i < 2; i++ {
		wg.Add(1)
		go func(idx int) {
			defer wg.Done()
			<-start
			photo := &DownloadedPhoto{
				URL:      sharedURL,
				Title:    "Concurrent",
				FileName: "concurrent.jpg",
				Status:   "downloaded",
			}
			duplicate := &InboxItem{
				ProviderID: "webgallery",
				DedupeKey:  "webgallery:concurrent",
				Status:     "duplicate",
				Reason:     "url_hash already kept",
			}
			results[idx], errs[idx] = db.RecordDownloadOrDuplicate(photo, duplicate)
		}(i)
	}
	close(start)
	wg.Wait()

	for i, err := range errs {
		if err != nil {
			t.Fatalf("goroutine %d errored: %v", i, err)
		}
	}

	wins := 0
	for _, kept := range results {
		if kept {
			wins++
		}
	}
	if wins != 1 {
		t.Fatalf("expected exactly one winner on the url_hash unique guard, got %d", wins)
	}

	var photoCount int64
	db.Model(&DownloadedPhoto{}).Where("url_hash = ?", HashURL(sharedURL)).Count(&photoCount)
	if photoCount != 1 {
		t.Fatalf("expected exactly one stored photo, got %d", photoCount)
	}

	exceptions, total, err := db.GetInboxExceptions(10, 0)
	if err != nil {
		t.Fatalf("GetInboxExceptions failed: %v", err)
	}
	if total != 1 || len(exceptions) != 1 || exceptions[0].Status != "duplicate" {
		t.Fatalf("expected the loser converted to one inbox duplicate, got total=%d items=%#v", total, exceptions)
	}
}

func TestPostgresConcurrentSameContentHashBothInsert(t *testing.T) {
	db := openPostgresTestDB(t)
	if err := Migrate(db.DB); err != nil {
		t.Fatalf("Migrate failed: %v", err)
	}

	// content_hash is an indexed (non-unique) column for cross-source dedupe, so
	// two distinct urls that share a content hash both insert; exact dedupe is a
	// higher-layer decision, not a DB unique violation.
	sharedContent := []byte("0123456789abcdef0123456789abcdef")
	var wg sync.WaitGroup
	errs := make([]error, 2)
	start := make(chan struct{})
	for i, u := range []string{"https://example.com/c1.jpg", "https://example.com/c2.jpg"} {
		wg.Add(1)
		go func(idx int, url string) {
			defer wg.Done()
			<-start
			errs[idx] = db.Create(&DownloadedPhoto{
				URL:         url,
				Title:       "Same Content",
				FileName:    "c.jpg",
				Status:      "downloaded",
				ContentHash: sharedContent,
			}).Error
		}(i, u)
	}
	close(start)
	wg.Wait()

	for i, err := range errs {
		if err != nil {
			t.Fatalf("content-hash insert %d errored: %v", i, err)
		}
	}

	var count int64
	db.Model(&DownloadedPhoto{}).Where("content_hash = ?", sharedContent).Count(&count)
	if count != 2 {
		t.Fatalf("expected both same-content rows to insert, got %d", count)
	}
}

func TestPostgresNewConnectsThroughBootGuards(t *testing.T) {
	dsn := os.Getenv("OKFOLIO_TEST_POSTGRES_DSN")
	if dsn == "" {
		t.Skip("set OKFOLIO_TEST_POSTGRES_DSN to run the Postgres-backed integration test")
	}

	// Passing the DSN verbatim through URL exercises the real boot path:
	// GuardAppDatabaseConfig, AssertNonLegacyDSN, the postgres dialect assertion,
	// pool tuning, and Migrate.
	db, err := New(&config.DatabaseConfig{URL: dsn})
	if err != nil {
		t.Fatalf("New through boot guards failed: %v", err)
	}
	if name := db.Dialector.Name(); name != "postgres" {
		t.Fatalf("expected postgres dialect from New, got %q", name)
	}

	// The legacy host guard refuses to even attempt a connection.
	if _, err := New(&config.DatabaseConfig{Host: "photoprism-mariadb", URL: dsn}); err == nil {
		t.Fatal("expected New to refuse a legacy DB_HOST")
	}
}

func assertIdentityByDefault(t *testing.T, db *DB) {
	t.Helper()
	var attidentity string
	err := db.DB.Raw(`
		SELECT a.attidentity
		FROM pg_attribute a
		JOIN pg_class c ON c.oid = a.attrelid
		WHERE c.relname = 'downloaded_photos' AND a.attname = 'id'`).Scan(&attidentity).Error
	if err != nil {
		t.Fatalf("identity probe failed: %v", err)
	}
	if attidentity != "d" {
		t.Fatalf("expected id GENERATED BY DEFAULT AS IDENTITY (attidentity='d'), got %q", attidentity)
	}
}

func indexExists(db *DB, name string) bool {
	var exists bool
	db.DB.Raw("SELECT EXISTS (SELECT 1 FROM pg_indexes WHERE tablename = 'downloaded_photos' AND indexname = ?)", name).Scan(&exists)
	return exists
}

func standaloneDownloadedAtIndexExists(db *DB) bool {
	var count int64
	db.DB.Raw(`
		SELECT COUNT(*)
		FROM pg_index i
		JOIN pg_class idx ON idx.oid = i.indexrelid
		JOIN pg_class tbl ON tbl.oid = i.indrelid
		WHERE tbl.relname = 'downloaded_photos'
		  AND i.indnatts = 1
		  AND (SELECT attname FROM pg_attribute WHERE attrelid = tbl.oid AND attnum = i.indkey[0]) = 'downloaded_at'`).Scan(&count)
	return count > 0
}

func urlHasBtree(db *DB) bool {
	var count int64
	db.DB.Raw(`
		SELECT COUNT(*)
		FROM pg_index i
		JOIN pg_class tbl ON tbl.oid = i.indrelid
		WHERE tbl.relname = 'downloaded_photos'
		  AND i.indnatts = 1
		  AND (SELECT attname FROM pg_attribute WHERE attrelid = tbl.oid AND attnum = i.indkey[0]) = 'url'`).Scan(&count)
	return count > 0
}

func names2HasEmbedding(t *testing.T, db *DB) bool {
	t.Helper()
	var exists bool
	db.DB.Raw(`
		SELECT EXISTS (
			SELECT 1 FROM information_schema.columns
			WHERE table_name = 'downloaded_photos' AND column_name = 'embedding'
		)`).Scan(&exists)
	return exists
}
